### PR TITLE
add an ut to start up query service for dev

### PR DESCRIPTION
**Pull request by Frapschen**

### CODE REVIEW

**Comment by JaredTan95** [comment]
looks like UT is working in progress?

**Comment by Frapschen** [comment]
> looks like UT is working in progress?

yes

**Comment by Frapschen** [comment]
@JaredTan95 please review

**Comment by JaredTan95** [comment]
> @JaredTan95 please review

how about add some `UT` check  CI stage within this PR?

ref: https://github.com/openinsight-proj/OpenInsight/issues/11

**Pull request merged**
